package com.untref.tesis.server.action.validator

val degreeCanNotBeNull = "Degree can not null"
val latitudeCanNotBeNull = "Latitude can not null"
val degreeCanNotBeLowerThan0 = "Degree can not lower than 0"
val longitudeCanNotBeNull = "Longitude can not be null"
val degreeCanNotBeHigherThan90ForLatitude = "degree can not be higher than 90 for latitude"
val minuteCanNotBeNull = "minute can not be null"
val minuteCanNotLowerThanZero = "minute can not lower than 0"
val minuteCanNotHigherOrEqualsThanSixteen = "minute can not higher or equals than 60"
val secondCanNotBeNull = "second can not be null"
val secondCanNotBeLowerThanZero = "second can not be lower than zero"
val secondCanNotBeHigherOrEqualsThanSixty = "second can not be higher or equals than 60"
val longitudeDegreeCanNotBeNull = "longitude degree can not be null"
val longitudeDegreeCanNotLowerThanZero = "longitude degree can not lower than 0"
val longitudeDegreeCanNotHigherThanOneHundredEighteen = "longitude degree can not higher  than one hundred eighteen"
val longitudeMinuteCanNotBeNull = "longitude minute can not be null"
val longitudeMinuteCanNotLowerZero = "longitude minute can not lower than 0"
val longitudeMinuteCanNotHigherOrEqualsThan60 = "longitude minute can not higher or equals than 60"