package com.untref.tesis.server.alert.domain

const val degreeCanNotBeLowerThan0 = "Degree can not lower than 0"
const val degreeCanNotBeHigherThan90ForLatitude = "degree can not be higher than 90 for latitude"
const val minuteCanNotLowerThanZero = "minute can not lower than 0"
const val minuteCanNotHigherOrEqualsThanSixteen = "minute can not higher or equals than 60"
const val secondCanNotBeLowerThanZero = "second can not be lower than zero"
const val secondCanNotBeHigherOrEqualsThanSixty = "second can not be higher or equals than 60"
const val longitudeDegreeCanNotLowerThanZero = "longitude degree can not lower than 0"
const val longitudeDegreeCanNotHigherThanOneHundredEighteen = "longitude degree can not higher  than one hundred eighteen"
const val longitudeMinuteCanNotLowerZero = "longitude minute can not lower than 0"
const val longitudeMinuteCanNotHigherOrEqualsThan60 = "longitude minute can not higher or equals than 60"
const val longitudeSecondCanNotLowerThan0 = "longitude second can not lower than 0"
const val longitudeSecondCanNotHigherOrEqualsThan60 = "longitude second can not higher or equals than 60"
const val latitudeCardinalPointCanNotBeEast = "latitude cardinal point can not be east"
const val latitudeCardinalPointCanNotBeWest = "latitude cardinal point can not be west"
const val longitudeCardinalPointCanNotBeNorth = "longitude cardinal point can not be north"
const val longitudeCardinalPointCanNotBeSouth = "longitude cardinal point can not be south"